version: '2'
services:
  kolab:
    restart: on-failure:1
    image: kvaps/kolab:16
    hostname: mail
    domainname:  retail.aptekivita.ru
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /tmp/kolab/data:/data:rw
      - /tmp/kolab/config:/config:rw
      - /tmp/kolab/spool:/spool:rw
      - /tmp/kolab/log:/log:rw
    tmpfs:
      - /run
    environment:
      - TZ=Europe/Samara
      - LDAP_ADMIN_PASS=Qq1234567*
      - LDAP_MANAGER_PASS=Qq1234567*
      - LDAP_CYRUS_PASS=Qq1234567*
      - LDAP_KOLAB_PASS=Qq1234567*
      - MYSQL_ROOT_PASS=Qq1234567*
      - MYSQL_KOLAB_PASS=Qq1234567*
      - MYSQL_ROUNDCUBE_PASS=Qq1234567*
      - KOLAB_DEFAULT_LOCALE=ru_RU
#      - LE_RENEW_HOOK=docker restart @CONTAINER_NAME@
    ports:
      - '80:80'
      - '443:443'
      - '25:25'
      - '587:587'
      - '110:110'
      - '995:995'
      - '143:143'
      - '993:993'
      - '4190:4190'
      - '389:389'
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    tty: true
